name: Test PowerShell on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test
        shell: pwsh
        run: |
          $PesterPreference.Run.Path = "./powershell"
          $PesterPreference.CodeCoverage.Enabled = $true
          $PesterPreference.CodeCoverage.Path = "./powershell/*.ps*1"
          Invoke-Pester -Configuration $PesterPreference
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./.codecov.yml  # Optional
          fail_ci_if_error: true  # Optional
